name: Déployer la Newsletter

on:
  push:
    branches:
      - main
    paths:
      - 'newsletters/**'

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Déployer sur la branche gh-pages du dépôt newsletter-portfolio
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        repository: SiaSia-dev/newsletter-portfolio
        branch: gh-pages
        folder: newsletters
        token: ${{ secrets.DEPLOY_TOKEN }}
        clean: true