name: Publication sur LinkedIn

on:
  #workflow_run:
  # workflows: ["Génération et Déploiement de Newsletter"]
  #  types:
  #    - completed
  workflow_dispatch:  # Permet de lancer manuellement

# Ajout des permissions pour permettre l'écriture dans le dépôt
permissions:
  contents: write

jobs:
  publish-linkedin:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
              
      - name: Checkout newsletter repository
        uses: actions/checkout@v3
        with:
          repository: SiaSia-dev/newsletter-portfolio
          path: newsletter-portfolio
          token: ${{ secrets.DEPLOY_TOKEN }}
          ref: gh-pages
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Publish to LinkedIn
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_PERSON_ID: ${{ secrets.LINKEDIN_PERSON_ID }}
          NEWSLETTERS_DIR: ${{ github.workspace }}/newsletter-portfolio
          GITHUB_USERNAME: SiaSia-dev
          GITHUB_REPO: newsletter-portfolio
        run: |
          # S'assurer que le répertoire newsletters existe
          mkdir -p ${{ github.workspace }}/newsletter-portfolio
          
          # Vérification du contenu du répertoire
          echo "Fichiers disponibles pour publication LinkedIn:"
          ls -la ${{ github.workspace }}/newsletter-portfolio
          
          # Exécuter le script de publication LinkedIn
          python scripts/linkedin_publisher.py

      - name: Enregistrer la publication
        if: success()
        run: |
          echo "Publication sur LinkedIn effectuée le $(date)" >> publications_log.txt
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Action"
          git add publications_log.txt
          git commit -m "Enregistrement de la publication LinkedIn du $(date)"
          git push