name: Publication sur LinkedIn

on:
  workflow_run:
    workflows: ["Génération de Newsletter LinkedIn"]
    types:
      - completed
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  publish-linkedin:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Publish to LinkedIn
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_PERSON_ID: ${{ secrets.LINKEDIN_PERSON_ID }}
          NEWSLETTERS_DIR: ${{ github.workspace }}/newsletters
          GITHUB_USERNAME: SiaSia-dev
          GITHUB_REPO: newsletter-portfolio
        run: |
          # S'assurer que le répertoire newsletters existe
          mkdir -p ${{ github.workspace }}/newsletters
          python scripts/linkedin_publisher.py